### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by cevarief** [yccphp/laravel-5-blog#1]
SQLite Database : 
[Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'keyword' on table 'article'.

**Comment by yccphp** [comment]
hi,Did you solve the question？

**Comment by GreatMonkeys** [comment]
想看回复功能

2015-08-06 13:22 GMT+08:00 袁超 <notifications@github.com>:

**Comment by yccphp** [comment]
@GreatMonkeys  进入 www.phpyc.com 查看
