### ISSUE TITLE
发现404页面没有调用哦。

### ISSUE THREAD

**Issue by DavidWangTM** [yccphp/laravel-5-blog#12]
![image](https://cloud.githubusercontent.com/assets/3624373/12188313/07eda2d6-b5ef-11e5-99da-e68be046d7cf.png)
这里是URL地址：http://www.phpyc.com/article/100

**Comment by yccphp** [comment]
是的，熟悉这个项目的知道，这个项目因主题侵权，更换过主题，而新主题暂时没有做404页面
