### ISSUE TITLE
麻烦一下，我有一个小小请求

### ISSUE THREAD

**Issue by wangmingxv** [yccphp/laravel-5-blog#16]
你可不可以把你这个项目的数据库导出来给我一份，我现在按你说的方法，发现数据库不是太完整，另外我也想加一下咱的群，方便以后有啥问题请教你，谢谢，打扰了，我的QQ：751066209

**Comment by yccphp** [comment]
数据库字段，在迁移文件中都存在的，是完整的～需要自己添加内容
