### ISSUE TITLE
Mews\Captcha\CaptchaServiceProvider::class

### ISSUE THREAD

**Issue by todo369** [yccphp/laravel-5-blog#3]
config/app.php(line 153):
Mews\Captcha\CaptchaServiceProvider::class

这个撒意思？
这什么语法，什么意思，没见过啊。

**Comment by sylarXu** [comment]
是php的一个新特性，获取类名称的

**Comment by todo369** [comment]
ok,不知是哪个PHP版本？手册在哪里？
我仅在这comment里发现 http://php.net/manual/en/language.oop5.constants.php
