### ISSUE TITLE
建议删除vendor文件夹和composer.lock文件

### ISSUE THREAD

**Issue by shellus** [yccphp/laravel-5-blog#4]
1、会有composer package兼容问题，如果某个package依赖某个php扩展。install过程中可以被发现
2、git clone的速度是个大问题。
3、使用composer推荐做法。
4、强制大家认识composer

**Comment by yccphp** [comment]
感谢建议，会在以后的版本迭代中删除

**Comment by yccphp** [comment]
已删除
