### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by shellus** [yccphp/laravel-5-blog#5]
public static function getTagArray()
    {
        $tagList = self::getTagModelAll();
        if (!empty($tag)) {
            foreach ($tagList as $tag) {
                self::$tags[$tag->id] = $tag->name;
            }
        }
        return self::$tags;
    }
真的有必要这样缓存吗？
可以用Model类自带的缓存啊。你这多写了多少代码啊。。。

**Comment by yccphp** [comment]
感谢提醒啦～
