### ISSUE TITLE
分页功能没效果

### ISSUE THREAD

**Issue by gaomingyang** [yccphp/laravel-5-blog#7]
分页功能点击后没有效果，第二页和第一页内容一样。

**Comment by yccphp** [comment]
你自己本地？

**Comment by gaomingyang** [comment]
是的啊 代码拉到本地后配置起来，发现后台用户列表分页不生效。

**Comment by yccphp** [comment]
我会检查此问题是否存在，如果存在将会修复，感谢关注

**Comment by gaomingyang** [comment]
抱歉，后来发现是我本地nginx配置没做好，代码分页那边没问题。

**Comment by yccphp** [comment]
没事，欢迎入群 `365969825 ` ，或者来 [http://www.laravel.ren/forum](http://www.laravel.ren/forum) 来交流
