### ISSUE TITLE
今日启动2.0计划

### ISSUE THREAD

**Issue by yccphp** [yccphp/laravel-5-blog#8]
将会继续完成以下事情：
1. 新的主题设计
2. 代码优化
3. 统计功能

**Comment by yuvista** [comment]
这个必须支持一下

**Comment by MerlinFeng** [comment]
Great！ 哈哈

**Comment by skywingfs** [comment]
希望越来越完善，支持个~

**Comment by Jarvis5780** [comment]
厉害！！

**Comment by EnzoLiuCN** [comment]
**小菜一枚，问一个问题：
为什么没有vendor文件夹呢？php artisan list的时候报错了...**

**Comment by yccphp** [comment]
@EnzoLiuCN  需要执行 composer install
