### ISSUE TITLE
Is there an easy way to change language to english?

### ISSUE THREAD

**Issue by vesper8** [yccphp/laravel-5-blog#9]
I really like your boilerplate here. I tried changing the locale in the app.php from chinese to english but it seemed to have no effect. All the menus are still in chinese. It would be great if you could switch between the two languages :)

**Comment by hto** [comment]
I'm about to finish the translation

**Comment by vesper8** [comment]
awesome!!

**Comment by yccphp** [comment]
cool，I'll try my best to finish
